name: Personal website CI for GitHub pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Setup node, cache dependencies
        uses: pnpm/action-setup@v2
        with:
          version: "8"

      - run: pnpm install
      - run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
